[package]
name = "minesweeper-e2e"
version = "0.1.0"
edition = "2024"
rust-version = "1.94.0"

[dependencies]
thirtyfour = "0.36.1"
tokio = { version = "1.50.0", features = ["rt", "rt-multi-thread", "macros"] }
netstat2 = "0.11"
sysinfo = "0.38.4"
anyhow = "1.0.102"
log = "0.4.29"
flexi_logger = "0.31.8"
reqwest = { version = "0.13.1", features = ["json", "gzip"] }